/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */
import { recommended } from './configs/recommended';
import twLogicalProperties from './rules/no-physical-properties';

export const configs = {
  recommended,
};

export const rules = {
  'tw-logical-properties': twLogicalProperties,
};
