/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */
import { recommended } from './configs/recommended';
import logicatProperties from './rules/tw-logical-properties'

export const configs = {
    recommended
};

export const rules = {
    'logical-properties': logicatProperties
};
